apiVersion: v1
kind: Service
metadata:
  name: bind9
spec:
  selector:
    app.kubernetes.io/name: bind9
    app.kubernetes.io/instance: ns
  ports:
    - port: 53
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    - port: 53
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
    - port: 9000
      targetPort: webhook
      protocol: TCP
      name: webhook
