apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - secrets.yaml
namespace: bind9-ns1
namePrefix: ns1-
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: ns1
      app.kubernetes.io/name: bind9
configMapGenerator:
  - name: bind9-netbox-config
    literals:
      - NETBOX_URL=http://netbox.netbox.svc.cluster.local/
      - NETBOX_DNS_NAMESERVER=ns1.example.com
